version: "3.3"

services:
  database:
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5000:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    build:
      context: ./Dr.Trash-DB
    networks:
      - default

volumes:
  db_data:
