version: '3.3'

services:
  database:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dr_trash
      APPLICATION_SCHEMA: application
      APPLICATION_USERNAME: application
      APPLICATION_PASSWORD: password
      DEVELOPER_USERNAME: developer
      DEVELOPER_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - db-data:/var/lib/postgresql/data
    build:
      context: ./Dr.Trash-DB
    networks:
      - default

  cache:
    image: redis:7.0.4-alpine
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default

  http:
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_USER: ${DATABASE_APPLICATION_USERNAME}
      DATABASE_HOST: database
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: ${DATABASE_APPLICATION_SCHEMA}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRES_IN: 20m
      JWT_REFRESH_EXPIRES_IN: 2h
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CALLBACK_URL: ${KAKAO_CALLBACK_URL}
      REDIS_HOST: cache
      REDIS_PORT: 6379
    ports:
      - '3000:3000'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./Dr.Trash-BE/src:/app/src:ro
    build:
      context: ./Dr.Trash-BE
    networks:
      - default

  amqp:
    ports:
      - '5672:5672'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    build:
      context: ./Dr.Trash-AMQP
    networks:
      - default

volumes:
  db-data:
