version: '3.3'

services:
  database:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dr_trash
      APPLICATION_SCHEMA: application
      APPLICATION_USERNAME: application
      APPLICATION_PASSWORD: password
      DEVELOPER_USERNAME: developer
      DEVELOPER_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - db-data:/var/lib/postgresql/data
    build:
      context: ./Dr.Trash-DB
    networks:
      - default

volumes:
  db-data:
