#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$APPLICATION_USERNAME" PASSWORD '$APPLICATION_PASSWORD';

    GRANT USAGE ON SCHEMA "$APPLICATION_SCHEMA" TO "$APPLICATION_USERNAME";
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "$APPLICATION_SCHEMA" TO "$APPLICATION_USERNAME";
    GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA "$APPLICATION_SCHEMA" TO "$APPLICATION_USERNAME";

    CREATE ROLE "$DEVELOPER_USERNAME" WITH LOGIN PASSWORD '$DEVELOPER_PASSWORD';

    GRANT ALL PRIVILEGES ON SCHEMA "$APPLICATION_SCHEMA" TO "$DEVELOPER_USERNAME";
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "$APPLICATION_SCHEMA" TO "$DEVELOPER_USERNAME";
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "$APPLICATION_SCHEMA" TO "$DEVELOPER_USERNAME";
EOSQL
