#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE SCHEMA $APPLICATION_SCHEMA AUTHORIZATION postgres;

    CREATE TABLE $APPLICATION_SCHEMA.user (
        id SERIAL,
        name VARCHAR(32) NOT NULL,
        image_uri VARCHAR(256) NOT NULL,
        point INTEGER NOT NULL,

        PRIMARY KEY (id)
    );

    CREATE TABLE $APPLICATION_SCHEMA.oauth (
        user_id INTEGER NOT NULL,
        provider VARCHAR(32) NOT NULL,
        id VARCHAR(128) NOT NULL,

        PRIMARY KEY (provider, id)
    );

    CREATE TABLE $APPLICATION_SCHEMA.trashcan (
        id SERIAL,
        manager_id INTEGER,
        name VARCHAR(32),
        description VARCHAR(256),
        latitude FLOAT,
        longitude FLOAT,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),

        PRIMARY KEY (id),
        FOREIGN KEY (manager_id) REFERENCES $APPLICATION_SCHEMA.user(id)
    );

    CREATE TABLE $APPLICATION_SCHEMA.article (
        id SERIAL,
        author_id INTEGER NOT NULL,
        title VARCHAR(32) NOT NULL,
        content VARCHAR(1024) NOT NULL,
        like_count INTEGER NOT NULL DEFAULT 0,
        view_count INTEGER NOT NULL DEFAULT 0,
        hate_count INTEGER NOT NULL DEFAULT 0,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

        PRIMARY KEY (id),
        FOREIGN KEY (author_id) REFERENCES $APPLICATION_SCHEMA.user(id)
    );

    CREATE TABLE $APPLICATION_SCHEMA.comment (
        id SERIAL,
        author_id INTEGER NOT NULL,
        article_id INTEGER NOT NULL,
        content VARCHAR(1024) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
        like_count INTEGER NOT NULL DEFAULT 0,
        hate_count INTEGER NOT NULL DEFAULT 0,

        PRIMARY KEY (id),
        FOREIGN KEY (author_id) REFERENCES $APPLICATION_SCHEMA.user(id),
        FOREIGN KEY (article_id) REFERENCES $APPLICATION_SCHEMA.article(id)
    );

    CREATE TABLE $APPLICATION_SCHEMA.achievement (
        id SERIAL,
        name VARCHAR(32) NOT NULL,
        description VARCHAR(256) NOT NULL,
        image_uri VARCHAR(256) NOT NULL,

        PRIMARY KEY (id)
    );

    CREATE TABLE $APPLICATION_SCHEMA.achiever (
        user_id INTEGER NOT NULL,
        achievement_id INTEGER NOT NULL,
        achieved_at TIMESTAMP NOT NULL DEFAULT NOW(),

        PRIMARY KEY (user_id, achievement_id),
        FOREIGN KEY (user_id) REFERENCES $APPLICATION_SCHEMA.user(id),
        FOREIGN KEY (achievement_id) REFERENCES $APPLICATION_SCHEMA.achievement(id)
    );

    CREATE USER $APPLICATION_USERNAME PASSWORD '$APPLICATION_PASSWORD';

    GRANT USAGE ON SCHEMA $APPLICATION_SCHEMA TO $APPLICATION_USERNAME;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA $APPLICATION_SCHEMA TO $APPLICATION_USERNAME;
    GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA $APPLICATION_SCHEMA TO $APPLICATION_USERNAME;

    CREATE ROLE $DEVELOPER_USERNAME WITH LOGIN PASSWORD '$DEVELOPER_PASSWORD';

    GRANT ALL PRIVILEGES ON SCHEMA $APPLICATION_SCHEMA TO $DEVELOPER_USERNAME;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA $APPLICATION_SCHEMA TO $DEVELOPER_USERNAME;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA $APPLICATION_SCHEMA TO $DEVELOPER_USERNAME;
EOSQL
